// ============================================================
//  SPELLING BEE PREP — APP LOGIC
//  Do NOT edit this file. Add words in data.js only.
// ============================================================

(function () {
  "use strict";

  // ── State ──────────────────────────────────────────────────
  let deck = [];
  let current = 0;
  let revealed = false;
  let filterTopic = "all";

  // ── DOM refs ───────────────────────────────────────────────
  const $ = id => document.getElementById(id);
  const counterEl   = $("counter");
  const topicBadge  = $("topic-badge");
  const posEl       = $("pos-value");
  const meaningEl   = $("meaning-value");
  const sentenceEl  = $("sentence-value");
  const revealBox   = $("reveal-box");
  const revealWord  = $("reveal-word");
  const topicFilter = $("topic-filter");
  const progressBar = $("progress-bar");

  // ── Build topic filter ─────────────────────────────────────
  function buildTopicFilter() {
    const topics = [...new Set(WORDS.map(w => w.topic).filter(Boolean))].sort();
    topics.forEach(t => {
      const opt = document.createElement("option");
      opt.value = t;
      opt.textContent = t.charAt(0).toUpperCase() + t.slice(1);
      topicFilter.appendChild(opt);
    });
  }

  // ── Shuffle (Fisher-Yates) ─────────────────────────────────
  function shuffle(arr) {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  }

  // ── Load / filter deck ─────────────────────────────────────
  function loadDeck() {
    const source = filterTopic === "all"
      ? WORDS
      : WORDS.filter(w => w.topic === filterTopic);
    deck = shuffle(source);
    current = 0;
    renderCard();
  }

  // ── Render current card ────────────────────────────────────
  function renderCard() {
    if (!deck.length) {
      counterEl.textContent = "No words";
      return;
    }
    const w = deck[current];
    revealed = false;

    // Counter & progress
    counterEl.textContent = `${current + 1} / ${deck.length}`;
    progressBar.style.width = `${((current + 1) / deck.length) * 100}%`;

    // Topic badge
    if (w.topic) {
      topicBadge.textContent = w.topic;
      topicBadge.style.display = "inline-block";
    } else {
      topicBadge.style.display = "none";
    }

    // Difficulty class on body
    document.body.dataset.difficulty = w.difficulty || "medium";

    // Info panels — reset to icon-only state
    collapseInfo();

    // Reveal box — reset
    revealBox.classList.remove("revealed");
    revealWord.textContent = "";
    revealBox.querySelector(".reveal-hint").style.display = "flex";
    revealWord.style.display = "none";
  }

  function collapseInfo() {
    ["pos", "meaning", "sentence"].forEach(key => {
      $(key + "-panel").classList.remove("open");
    });
    posEl.textContent = "";
    meaningEl.textContent = "";
    sentenceEl.textContent = "";
  }

  // ── Toggle info panels ─────────────────────────────────────
  window.togglePanel = function (key) {
    const panel = $(key + "-panel");
    const w = deck[current];
    if (!w) return;

    if (panel.classList.contains("open")) {
      panel.classList.remove("open");
      $(key + "-value").textContent = "";
    } else {
      panel.classList.add("open");
      if (key === "pos") $(key + "-value").textContent = w.pos;
      if (key === "meaning") $(key + "-value").textContent = w.meaning;
      if (key === "sentence") $(key + "-value").textContent = w.sentence;
    }
  };

  // ── Reveal spelling ────────────────────────────────────────
  window.revealSpelling = function () {
    if (revealed) return;
    revealed = true;
    const w = deck[current];
    revealBox.classList.add("revealed");
    revealBox.querySelector(".reveal-hint").style.display = "none";
    revealWord.style.display = "block";
    revealWord.textContent = w.word;
  };

  // ── Speech ─────────────────────────────────────────────────
  function speak(rate) {
    if (!window.speechSynthesis) return;
    window.speechSynthesis.cancel();
    const w = deck[current];
    if (!w) return;
    const utter = new SpeechSynthesisUtterance(w.word);
    utter.lang = "en-GB";
    utter.rate = rate;

    // Prefer a British English voice if available
    const voices = window.speechSynthesis.getVoices();
    const gbVoice = voices.find(v => v.lang === "en-GB") || null;
    if (gbVoice) utter.voice = gbVoice;

    window.speechSynthesis.speak(utter);
  }

  window.listenNormal = () => speak(1.0);
  window.listenSlow   = () => speak(0.6);

  // Voices may load async
  window.speechSynthesis.onvoiceschanged = () => {};

  // ── Mark correct / incorrect ───────────────────────────────
  window.markResult = function (correct) {
    const btn = $(correct ? "btn-correct" : "btn-incorrect");
    btn.classList.add("flash");
    setTimeout(() => btn.classList.remove("flash"), 400);

    setTimeout(() => {
      if (current < deck.length - 1) {
        current++;
        renderCard();
      } else {
        showFinish();
      }
    }, 350);
  };

  // ── Finish screen ──────────────────────────────────────────
  function showFinish() {
    $("card-area").style.display = "none";
    $("finish-screen").style.display = "flex";
  }

  window.restartDeck = function () {
    $("finish-screen").style.display = "none";
    $("card-area").style.display = "block";
    loadDeck();
  };

  // ── Shuffle button ─────────────────────────────────────────
  $("btn-shuffle").addEventListener("click", loadDeck);

  // ── Topic filter ───────────────────────────────────────────
  topicFilter.addEventListener("change", () => {
    filterTopic = topicFilter.value;
    loadDeck();
  });

  // ── Init ───────────────────────────────────────────────────
  buildTopicFilter();
  loadDeck();
})();
