
    const masterData = [
      // Clothes & Accessories
      { topic: "Clothes & Accessories", word: "blouse", pos: "noun", def: "A piece of clothing like a shirt, typically worn by women.", sen: "She wore a smart white blouse to the office." },
      { topic: "Clothes & Accessories", word: "trainers", pos: "noun", def: "Soft sports shoes suitable for playing sport or for casual wear.", sen: "He tied the laces on his trainers before going for a run." },
      { topic: "Clothes & Accessories", word: "swimming costume", pos: "noun", def: "A piece of clothing worn for swimming, especially by women and girls.", sen: "She bought a new swimming costume for her holiday by the sea." },
      { topic: "General", word: "a/an", pos: "det", def: "-", sen: "-" },
      { topic: "General", word: "a few", pos: "det, adj & pron", def: "-", sen: "-" },
      { topic: "Personal Feelings, Opinions and Experiences", word: "able", pos: "adj", def: "-", sen: "-" },
      { topic: "General", word: "a/an", pos: "det", def: "-", sen: "-" },
      { topic: "General", word: "a few", pos: "det, adj & pron", def: "-", sen: "-" },
      { topic: "Personal Feelings, Opinions and Experiences", word: "able", pos: "adj", def: "-", sen: "-" },
      { topic: "General", word: "about", pos: "adv & prep", def: "-", sen: "-" },
      { topic: "General", word: "above", pos: "adv & prep", def: "-", sen: "-" },
      { topic: "Health, Medicine and Exercise", word: "accident", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "across", pos: "adv & prep", def: "-", sen: "-" },
      { topic: "Entertainment and Media", word: "act", pos: "n & v", def: "-", sen: "-" },
      { topic: "General", word: "action", pos: "adj", def: "-", sen: "-" },
      { topic: "General", word: "activity", pos: "n", def: "-", sen: "-" },
      { topic: "Entertainment and Media", word: "actor", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "actually", pos: "adv", def: "-", sen: "-" },
      { topic: "Documents and Texts", word: "ad", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "add", pos: "v", def: "-", sen: "-" },
      { topic: "Communication and Technology", word: "address", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "adult", pos: "adj & n", def: "-", sen: "-" },
      { topic: "Education", word: "advanced", pos: "adj", def: "-", sen: "-" },
      { topic: "Entertainment and Media", word: "adventure", pos: "n", def: "-", sen: "-" },
      { topic: "Documents and Texts", word: "advert", pos: "n", def: "-", sen: "-" },
      { topic: "Entertainment and Media", word: "advertisement", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "advice", pos: "n", def: "-", sen: "-" },
      { topic: "Travel and Transport", word: "aeroplane", pos: "n", def: "-", sen: "-" },
      { topic: "Personal Feelings, Opinions and Experiences", word: "afraid", pos: "adj", def: "-", sen: "-" },
      { topic: "General", word: "after", pos: "adv & prep", def: "-", sen: "-" },
      { topic: "Time", word: "afternoon", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "afterwards", pos: "adv", def: "-", sen: "-" },
      { topic: "General", word: "again", pos: "adv", def: "-", sen: "-" },
      { topic: "General", word: "against", pos: "prep", def: "-", sen: "-" },
      { topic: "General", word: "age", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "aged", pos: "adj", def: "-", sen: "-" },
      { topic: "General", word: "ago", pos: "adv", def: "-", sen: "-" },
      { topic: "General", word: "agree", pos: "v", def: "-", sen: "-" },
      { topic: "The Natural World", word: "air", pos: "n", def: "-", sen: "-" },
      { topic: "Travel and Transport", word: "airport", pos: "n", def: "-", sen: "-" },
      { topic: "Appliances", word: "alarm clock", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "album", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "all", pos: "adv, det & pron", def: "-", sen: "-" },
      { topic: "General", word: "all kinds of", pos: "det & pron", def: "-", sen: "-" },
      { topic: "General", word: "allow", pos: "v", def: "-", sen: "-" },
      { topic: "General", word: "all right/alright", pos: "adj, adv & exclam", def: "-", sen: "-" },
      { topic: "General", word: "all sorts of", pos: "det & pron", def: "-", sen: "-" },
      { topic: "General", word: "all the time", pos: "det", def: "-", sen: "-" },
      { topic: "General", word: "almost", pos: "adv", def: "-", sen: "-" },
      { topic: "Personal Feelings, Opinions and Experiences", word: "alone", pos: "adj & adv", def: "-", sen: "-" },
      { topic: "General", word: "along", pos: "prep", def: "-", sen: "-" },
      { topic: "General", word: "already", pos: "adv", def: "-", sen: "-" },
      { topic: "General", word: "alright", pos: "adj, adv & exclam", def: "-", sen: "-" },
      { topic: "General", word: "also", pos: "adv", def: "-", sen: "-" },
      { topic: "General", word: "always", pos: "adv", def: "-", sen: "-" },
      { topic: "Time", word: "a.m.", pos: "adv", def: "-", sen: "-" },
      { topic: "Personal Feelings, Opinions and Experiences", word: "amazed", pos: "adj", def: "-", sen: "-" },
      { topic: "Personal Feelings, Opinions and Experiences", word: "amazing", pos: "adj", def: "-", sen: "-" },
      { topic: "Health, Medicine and Exercise", word: "ambulance", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "among", pos: "prep", def: "-", sen: "-" },
      { topic: "General", word: "an", pos: "det", def: "-", sen: "-" },
      { topic: "General", word: "and", pos: "conj", def: "-", sen: "-" },
      { topic: "Personal Feelings, Opinions and Experiences", word: "angry", pos: "adj", def: "-", sen: "-" },
      { topic: "General", word: "animal", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "another", pos: "det & pron", def: "-", sen: "-" },
      { topic: "General", word: "answer", pos: "n & v", def: "-", sen: "-" },
      { topic: "General", word: "any", pos: "det & pron", def: "-", sen: "-" },
      { topic: "General", word: "anybody", pos: "pron", def: "-", sen: "-" },
      { topic: "General", word: "anymore", pos: "adv", def: "-", sen: "-" },
      { topic: "General", word: "anyone", pos: "pron", def: "-", sen: "-" },
      { topic: "General", word: "anything", pos: "pron", def: "-", sen: "-" },
      { topic: "General", word: "anyway", pos: "adv", def: "-", sen: "-" },
      { topic: "General", word: "anywhere", pos: "adv", def: "-", sen: "-" },
      { topic: "House and Home", word: "apartment", pos: "n", def: "-", sen: "-" },
      { topic: "Places: Buildings", word: "apartment building", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "app", pos: "n", def: "-", sen: "-" },
      { topic: "Food and Drink", word: "apple", pos: "n", def: "-", sen: "-" },
      { topic: "Health, Medicine and Exercise", word: "appointment", pos: "n", def: "-", sen: "-" },
      { topic: "Places: Countryside", word: "area", pos: "n", def: "-", sen: "-" },
      { topic: "Health, Medicine and Exercise", word: "arm", pos: "n", def: "-", sen: "-" },
      { topic: "House and Home", word: "armchair", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "around", pos: "adv & prep", def: "-", sen: "-" },
      { topic: "General", word: "arrive", pos: "v", def: "-", sen: "-" },
      { topic: "Entertainment and Media", word: "art", pos: "n", def: "-", sen: "-" },
      { topic: "Documents and Texts", word: "article", pos: "n", def: "-", sen: "-" },
      { topic: "Entertainment and Media", word: "artist", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "as", pos: "conj & adv & prep", def: "-", sen: "-" },
      { topic: "General", word: "ask", pos: "v", def: "-", sen: "-" },
      { topic: "Shopping", word: "assistant", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "as well", pos: "adv", def: "-", sen: "-" },
      { topic: "General", word: "as well (as)", pos: "prep", def: "-", sen: "-" },
      { topic: "General", word: "at", pos: "prep", def: "-", sen: "-" },
      { topic: "Communication and Technology", word: "at / @", pos: "prep", def: "-", sen: "-" },
      { topic: "General", word: "at all", pos: "prep phr", def: "-", sen: "-" },
      { topic: "General", word: "attractive", pos: "adj", def: "-", sen: "-" },
      { topic: "Family and Friends", word: "aunt", pos: "n", def: "-", sen: "-" },
      { topic: "The Natural World", word: "autumn", pos: "n", def: "-", sen: "-" },
      { topic: "General", word: "available", pos: "adj", def: "-", sen: "-" },
      { topic: "General", word: "away", pos: "adv", def: "-", sen: "-" },
      { topic: "Personal Feelings, Opinions and Experiences", word: "awesome", pos: "adj", def: "-", sen: "-" },
      { topic: "General", word: "awful", pos: "adj", def: "-", sen: "-" },

          
      // Technology
      { topic: "Communications & Technology", word: "download", pos: "verb", def: "To copy data from one computer system to another, typically over the internet.", sen: "It took a long time to download the large software file." },
      { topic: "Communications & Technology", word: "keyboard", pos: "noun", def: "A panel of keys that operates a computer or typewriter.", sen: "He typed the message quickly using his wireless keyboard." },
      { topic: "Communications & Technology", word: "password", pos: "noun", def: "A secret word or phrase used to gain admission to a computer system.", sen: "Make sure you choose a strong password to protect your account." },

      // Education
      { topic: "Education", word: "curriculum", pos: "noun", def: "The subjects comprising a course of study in a school or college.", sen: "Maths and Science are core parts of the school curriculum." },
      { topic: "Education", word: "dictionary", pos: "noun", def: "A book or electronic resource that lists the words of a language and gives their meaning.", sen: "If you don't know how to spell a word, look it up in the dictionary." },
      { topic: "Education", word: "composition", pos: "noun", def: "An essay, especially one written by a school student.", sen: "We had to write a short composition about our summer holidays." },

      // Food & Drink
      { topic: "Food & Drink", word: "biscuit", pos: "noun", def: "A small, baked, unleavened cake, typically crisp, flat, and sweet.", sen: "She enjoyed a cup of tea and a chocolate biscuit." },
      { topic: "Food & Drink", word: "recipe", pos: "noun", def: "A set of instructions for preparing a particular dish.", sen: "I followed my grandmother's recipe to bake the cake." },
      { topic: "Food & Drink", word: "delicious", pos: "adjective", def: "Highly pleasant to the taste.", sen: "The roast dinner they prepared was absolutely delicious." },

      // Health
      { topic: "Health & Exercise", word: "medicine", pos: "noun", def: "A compound or preparation used for the treatment or prevention of disease.", sen: "The doctor prescribed some medicine for her terrible cough." },
      { topic: "Health & Exercise", word: "ambulance", pos: "noun", def: "A vehicle specially equipped for taking sick or injured people to and from hospital.", sen: "They called an ambulance immediately after the accident." },
      { topic: "Health & Exercise", word: "bandage", pos: "noun", def: "A strip of woven material used to bind up a wound.", sen: "The nurse wrapped a clean bandage around his sprained ankle." }
    ];
