// ============================================================
//  SPELLING BEE PREP — WORD LIST
//  Add or remove words here. Never edit index.html or app.js.
//
//  Each word object supports these fields:
//    word        (required) — the correct British English spelling
//    pos         (required) — part of speech, e.g. "noun", "verb", "adjective"
//    meaning     (required) — a clear, concise definition
//    sentence    (required) — an example sentence using the word
//    difficulty  (optional) — "easy" | "medium" | "hard"  (default: "medium")
//    topic       (optional) — category label, e.g. "science", "literature"
// ============================================================

const WORDS = [
  {
    word: "acquiesce",
    pos: "verb",
    meaning: "To accept something reluctantly but without protest.",
    sentence: "She decided to acquiesce to her teacher's suggestion and revise her essay.",
    difficulty: "hard",
    topic: "behaviour"
  },
  {
    word: "conscientious",
    pos: "adjective",
    meaning: "Wishing to do one's work or duty well and thoroughly.",
    sentence: "The conscientious student double-checked every answer before submitting.",
    difficulty: "medium",
    topic: "character"
  },
  {
    word: "ephemeral",
    pos: "adjective",
    meaning: "Lasting for a very short time.",
    sentence: "The beauty of the cherry blossoms is ephemeral, fading within days.",
    difficulty: "hard",
    topic: "time"
  },
  {
    word: "liquefy",
    pos: "verb",
    meaning: "To make or become liquid.",
    sentence: "Extreme heat can liquefy metals that are usually solid.",
    difficulty: "medium",
    topic: "science"
  },
  {
    word: "miscellaneous",
    pos: "adjective",
    meaning: "Of various types or from different sources; assorted.",
    sentence: "The drawer was full of miscellaneous items with no obvious order.",
    difficulty: "medium",
    topic: "general"
  },
  {
    word: "occurrence",
    pos: "noun",
    meaning: "An incident or event that takes place.",
    sentence: "Rainfall in the desert is a rare occurrence.",
    difficulty: "easy",
    topic: "general"
  },
  {
    word: "pharaoh",
    pos: "noun",
    meaning: "A ruler in ancient Egypt.",
    sentence: "The pharaoh ordered the construction of a great pyramid.",
    difficulty: "medium",
    topic: "history"
  },
  {
    word: "questionnaire",
    pos: "noun",
    meaning: "A set of printed or written questions with spaces for answers.",
    sentence: "Participants were asked to fill in a questionnaire about their habits.",
    difficulty: "medium",
    topic: "general"
  },
  {
    word: "supersede",
    pos: "verb",
    meaning: "To take the place of something previously in authority or use.",
    sentence: "Digital cameras largely superseded film cameras in the early 2000s.",
    difficulty: "hard",
    topic: "technology"
  },
  { word: "a/an", pos: "det", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "a few", pos: "det, adj & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "able", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "about", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "above", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "accident", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "across", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "act", pos: "n & v", meaning: "-", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "action", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "activity", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "actor", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "actually", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "ad", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "add", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "address", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "adult", pos: "adj & n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "advanced", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "adventure", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "advert", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "advertisement", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "advice", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "aeroplane", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "afraid", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "after", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "afternoon", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "afterwards", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "again", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "against", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "age", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "aged", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "ago", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "agree", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "air", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "airport", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "alarm clock", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Appliances" },
{ word: "album", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all", pos: "adv, det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all kinds of", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "allow", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all right/alright", pos: "adj, adv & exclam", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all sorts of", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all the time", pos: "det", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "almost", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "alone", pos: "adj & adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "along", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "already", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "alright", pos: "adj, adv & exclam", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "also", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "always", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "a.m.", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "amazed", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "amazing", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "ambulance", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "among", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "an", pos: "det", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "and", pos: "conj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "angry", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "animal", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "another", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "answer", pos: "n & v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "any", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anybody", pos: "pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anymore", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anyone", pos: "pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anything", pos: "pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anyway", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anywhere", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "apartment", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "apartment building", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "app", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "apple", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "appointment", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "area", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "arm", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "armchair", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "around", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "arrive", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "art", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "article", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "artist", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "as", pos: "conj & adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "ask", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "assistant", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "as well", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "as well (as)", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "at", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "at / @", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "at all", pos: "prep phr", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "attractive", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "aunt", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "autumn", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "available", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "away", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "awesome", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "awful", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
  {
    word: "threshold",
    pos: "noun",
    meaning: "The level or point at which something starts to happen.",
    sentence: "The noise had reached the threshold at which it became unbearable.",
    difficulty: "easy",
    topic: "science"
  }
];
