// ============================================================
//  SPELLING BEE PREP — WORD LIST
//  Add or remove words here. Never edit index.html or app.js.
//
//  Each word object supports these fields:
//    word        (required) — the correct British English spelling
//    pos         (required) — part of speech, e.g. "noun", "verb", "adjective"
//    meaning     (required) — a clear, concise definition
//    sentence    (required) — an example sentence using the word
//    difficulty  (optional) — "easy" | "medium" | "hard"  (default: "medium")
//    topic       (optional) — category label, e.g. "science", "literature"
// ============================================================

const WORDS = [
  {
    word: "acquiesce",
    pos: "verb",
    meaning: "To accept something reluctantly but without protest.",
    sentence: "She decided to acquiesce to her teacher's suggestion and revise her essay.",
    difficulty: "hard",
    topic: "behaviour"
  },
  {
    word: "conscientious",
    pos: "adjective",
    meaning: "Wishing to do one's work or duty well and thoroughly.",
    sentence: "The conscientious student double-checked every answer before submitting.",
    difficulty: "medium",
    topic: "character"
  },
  {
    word: "ephemeral",
    pos: "adjective",
    meaning: "Lasting for a very short time.",
    sentence: "The beauty of the cherry blossoms is ephemeral, fading within days.",
    difficulty: "hard",
    topic: "time"
  },
  {
    word: "liquefy",
    pos: "verb",
    meaning: "To make or become liquid.",
    sentence: "Extreme heat can liquefy metals that are usually solid.",
    difficulty: "medium",
    topic: "science"
  },
  {
    word: "miscellaneous",
    pos: "adjective",
    meaning: "Of various types or from different sources; assorted.",
    sentence: "The drawer was full of miscellaneous items with no obvious order.",
    difficulty: "medium",
    topic: "general"
  },
  {
    word: "occurrence",
    pos: "noun",
    meaning: "An incident or event that takes place.",
    sentence: "Rainfall in the desert is a rare occurrence.",
    difficulty: "easy",
    topic: "general"
  },
  {
    word: "pharaoh",
    pos: "noun",
    meaning: "A ruler in ancient Egypt.",
    sentence: "The pharaoh ordered the construction of a great pyramid.",
    difficulty: "medium",
    topic: "history"
  },
  {
    word: "questionnaire",
    pos: "noun",
    meaning: "A set of printed or written questions with spaces for answers.",
    sentence: "Participants were asked to fill in a questionnaire about their habits.",
    difficulty: "medium",
    topic: "general"
  },
  {
    word: "supersede",
    pos: "verb",
    meaning: "To take the place of something previously in authority or use.",
    sentence: "Digital cameras largely superseded film cameras in the early 2000s.",
    difficulty: "hard",
    topic: "technology"
  },
  { word: "a/an", pos: "det", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "a few", pos: "det, adj & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "able", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "about", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "above", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "accident", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "across", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "act", pos: "n & v", meaning: "-", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "action", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "activity", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "actor", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "actually", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "ad", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "add", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "address", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "adult", pos: "adj & n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "advanced", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "adventure", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "advert", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "advertisement", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "advice", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "aeroplane", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "afraid", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "after", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "afternoon", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "afterwards", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "again", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "against", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "age", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "aged", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "ago", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "agree", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "air", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "airport", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "alarm clock", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Appliances" },
{ word: "album", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all", pos: "adv, det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all kinds of", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "allow", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all right/alright", pos: "adj, adv & exclam", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all sorts of", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all the time", pos: "det", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "almost", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "alone", pos: "adj & adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "along", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "already", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "alright", pos: "adj, adv & exclam", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "also", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "always", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "a.m.", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "amazed", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "amazing", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "ambulance", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "among", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "an", pos: "det", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "and", pos: "conj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "angry", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "animal", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "another", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "answer", pos: "n & v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "any", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anybody", pos: "pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anymore", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anyone", pos: "pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anything", pos: "pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anyway", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anywhere", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "apartment", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "apartment building", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "app", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "apple", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "appointment", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "area", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "arm", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "armchair", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "around", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "arrive", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "art", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "article", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "artist", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "as", pos: "conj & adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "ask", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "assistant", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "as well", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "as well (as)", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "at", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "at / @", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "at all", pos: "prep phr", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "attractive", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "aunt", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "autumn", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "available", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "away", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "awesome", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "awful", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "baby", pos: "n", meaning: "A very young child", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "back", pos: "adv, n & prep", meaning: "The rear part or return to a place", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "backpack", pos: "n", meaning: "A bag carried on the back", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bad", pos: "adj", meaning: "Not good; unpleasant", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "badly", pos: "adv", meaning: "In a way that is not good", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "badminton", pos: "n", meaning: "A sport played with rackets and a shuttlecock", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "bag", pos: "n", meaning: "A container used for carrying things", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "bake", pos: "v", meaning: "To cook in an oven", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "baker", pos: "n", meaning: "A person who makes bread and cakes", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "ball", pos: "n", meaning: "A round object used in games", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "balloon", pos: "n", meaning: "A small rubber bag filled with air", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "banana", pos: "n", meaning: "A long yellow fruit", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "band", pos: "n", meaning: "A group of musicians", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "bandage", pos: "n", meaning: "A cloth used to cover a wound", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "bank", pos: "n", meaning: "A place where money is kept", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "barbecue", pos: "n & v", meaning: "A meal cooked outdoors on a grill", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "baseball", pos: "n", meaning: "A game played with a bat and ball", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "basketball", pos: "n", meaning: "A game where you throw a ball through a hoop", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "bat", pos: "n", meaning: "Equipment used to hit a ball", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "bath", pos: "n & v", meaning: "Washing the body in a tub of water", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "bathing suit", pos: "n", meaning: "Clothes worn for swimming", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "bathroom", pos: "n", meaning: "A room for washing and using the toilet", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "bathtub", pos: "n", meaning: "A large container for washing the body", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "battery", pos: "n", meaning: "An object that provides electricity", sentence: "-", difficulty: "easy", topic: "Appliances" },
{ word: "be", pos: "v", meaning: "To exist or live", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "beach", pos: "n", meaning: "A sandy area by the sea", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "bean", pos: "n", meaning: "A seed of a plant used as food", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "bear", pos: "n", meaning: "A large, heavy wild animal", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "beard", pos: "n", meaning: "Hair growing on a man's chin", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "beautiful", pos: "adj", meaning: "Very attractive", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "because", pos: "conj", meaning: "For the reason that", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "become", pos: "v", meaning: "To begin to be something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "bed", pos: "n", meaning: "Furniture for sleeping", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "bedroom", pos: "n", meaning: "A room for sleeping", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "bee", pos: "n", meaning: "A yellow and black flying insect", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "beef", pos: "n", meaning: "Meat from a cow", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "before", pos: "adv, prep & conj", meaning: "Earlier than", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "begin", pos: "v", meaning: "To start", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "beginner", pos: "n", meaning: "A person starting to learn something", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "beginning", pos: "n", meaning: "The start of something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "behind", pos: "adv & prep", meaning: "At the back of", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "believe", pos: "v", meaning: "To think that something is true", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "bell", pos: "n", meaning: "A metal object that makes a ringing sound", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "belong", pos: "v", meaning: "To be the property of", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "below", pos: "adv & prep", meaning: "In a lower position", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "belt", pos: "n", meaning: "A strip of leather worn around the waist", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "beside", pos: "prep", meaning: "Next to", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "best", pos: "adj & adv", meaning: "Of the highest quality", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "better", pos: "adj & adv", meaning: "Higher in quality than something else", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "between", pos: "prep", meaning: "In the middle of two things", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "bicycle", pos: "n", meaning: "A vehicle with two wheels", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "big", pos: "adj", meaning: "Large in size", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "bike", pos: "n", meaning: "Short for bicycle or motorcycle", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bill", pos: "n", meaning: "A piece of paper showing money owed", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "bin", pos: "n", meaning: "A container for rubbish", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "biology", pos: "n", meaning: "The study of living things", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "bird", pos: "n", meaning: "An animal with feathers and wings", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "birth", pos: "n", meaning: "The time when a baby is born", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "birthday", pos: "n", meaning: "The day on which someone was born", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "biscuit", pos: "n", meaning: "A thin, flat, sweet cake", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "bit", pos: "n", meaning: "A small piece or amount", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "black", pos: "adj & n", meaning: "The darkest color", sentence: "-", difficulty: "easy", topic: "Colours" },
{ word: "blackboard", pos: "n", meaning: "A dark board used in schools", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "blanket", pos: "n", meaning: "A warm cover for a bed", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "block", pos: "n", meaning: "A large building or solid piece", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "blog", pos: "n", meaning: "A website with regular writing", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "blond(e)", pos: "adj", meaning: "Light-colored hair", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "blood", pos: "n", meaning: "Red liquid in the body", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "blouse", pos: "n", meaning: "A shirt for women", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "blue", pos: "adj & n", meaning: "The color of the sky", sentence: "-", difficulty: "easy", topic: "Colours" },
{ word: "board", pos: "n", meaning: "A flat piece of wood or card", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "board game", pos: "n", meaning: "A game played on a board", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "boat", pos: "n", meaning: "A small vehicle for traveling on water", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "body", pos: "n", meaning: "The whole physical structure of a person", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "boil", pos: "v", meaning: "To cook in very hot water", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "boiled", pos: "adj", meaning: "Cooked in boiling water", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "book", pos: "n & v", meaning: "Something to read or to reserve a place", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "bookcase", pos: "n", meaning: "A piece of furniture for books", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "booking", pos: "n", meaning: "A reservation", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bookshop", pos: "n", meaning: "A shop that sells books", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "boot", pos: "n", meaning: "A type of strong shoe covering the ankle", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "border", pos: "n", meaning: "The line between two countries", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bored", pos: "adj", meaning: "Feeling tired and unhappy because of no interest", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "boring", pos: "adj", meaning: "Not interesting", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "born", pos: "adj", meaning: "To come out of a mother's body", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "borrow", pos: "v", meaning: "To take something for a short time", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "boss", pos: "n", meaning: "A person in charge at work", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "both", pos: "det & pron", meaning: "Two people or things together", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "bottle", pos: "n", meaning: "A container for liquids", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "bottom", pos: "adj & n", meaning: "The lowest part of something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "bowl", pos: "n", meaning: "A round container for food", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "box", pos: "n", meaning: "A container with straight sides", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "boy", pos: "n", meaning: "A male child", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "boyfriend", pos: "n", meaning: "A male partner in a relationship", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "bracelet", pos: "n", meaning: "Jewellery worn around the wrist", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "brain", pos: "n", meaning: "The organ inside the head used for thinking", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "brake", pos: "n & v", meaning: "Something used to stop a vehicle", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bread", pos: "n", meaning: "A food made from flour and water", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "break", pos: "n & v", meaning: "To damage something or a short rest", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "breakfast", pos: "n", meaning: "The first meal of the day", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "bridge", pos: "n", meaning: "A structure built over a road or river", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bright", pos: "adj", meaning: "Full of light or intelligent", sentence: "-", difficulty: "easy", topic: "Colours" },
{ word: "brilliant", pos: "adj", meaning: "Very good or very bright", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "bring", pos: "v", meaning: "To take someone or something with you", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "broken", pos: "adj", meaning: "Damaged and not working", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "brother", pos: "n", meaning: "A male sibling", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "brown", pos: "adj & n", meaning: "The color of earth or wood", sentence: "-", difficulty: "easy", topic: "Colours" },
{ word: "brush", pos: "n & v", meaning: "An object used for cleaning or painting", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "build", pos: "v", meaning: "To make something by putting parts together", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "builder", pos: "n", meaning: "A person whose job is to build houses", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "building", pos: "n", meaning: "A structure with walls and a roof", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "burger", pos: "n", meaning: "Meat in a round bread roll", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "bus", pos: "n", meaning: "A large vehicle for many passengers", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "business", pos: "n", meaning: "Buying and selling goods or services", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "businessman", pos: "n", meaning: "A man who works in business", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "businesswoman", pos: "n", meaning: "A woman who works in business", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "bus station", pos: "n", meaning: "A place where buses start and end", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bus stop", pos: "n", meaning: "A place where a bus stops for people", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "busy", pos: "adj", meaning: "Working hard or having a lot to do", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "but", pos: "conj", meaning: "Used to introduce a different statement", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "butter", pos: "n", meaning: "A yellow fat made from milk", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "butterfly", pos: "n", meaning: "An insect with large colored wings", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "buy", pos: "v", meaning: "To get something by paying money", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "by", pos: "prep", meaning: "Beside or near", sentence: "-", difficulty: "easy", topic: "General" },
  
  
  {
    word: "threshold",
    pos: "noun",
    meaning: "The level or point at which something starts to happen.",
    sentence: "The noise had reached the threshold at which it became unbearable.",
    difficulty: "easy",
    topic: "science"
  }
];
