
/* ============================================================
//  3. APP.JS — SPELLING BEE PREP
//  Do NOT edit this file. Add words in data.js only.
// ============================================================
Instructions for GitHub:
Create a file named app.js and copy everything from 
"let deck = [];" down to the bottom.
========================================================= 
*/

  // ── State ──────────────────────────────────────────────────
  let deck = [];
  let current = 0;
  let revealed = false;
  let filterTopic = "all";
  let filterDifficulty = "all";

  // ── Build topic & difficulty filters ───────────────────────
  function buildFilters() {
    const topicFilter = document.getElementById("topic-filter");
    const difficultyFilter = document.getElementById("difficulty-filter");

    // Topics
    const topics = [...new Set(WORDS.map(w => w.topic).filter(Boolean))].sort();
    topics.forEach(t => {
      const opt = document.createElement("option");
      opt.value = t;
      opt.textContent = t.charAt(0).toUpperCase() + t.slice(1);
      topicFilter.appendChild(opt);
    });

    // Difficulties
    const difficulties = [...new Set(WORDS.map(w => w.difficulty).filter(Boolean))].sort();
    difficulties.forEach(d => {
      const opt = document.createElement("option");
      opt.value = d;
      opt.textContent = d.charAt(0).toUpperCase() + d.slice(1);
      difficultyFilter.appendChild(opt);
    });
  }

  // ── Shuffle (Fisher-Yates) ─────────────────────────────────
  function shuffle(arr) {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  }

  // ── Load / filter deck ─────────────────────────────────────
  function loadDeck() {
    const source = WORDS.filter(w => {
      const matchTopic = filterTopic === "all" ? true : w.topic === filterTopic;
      const matchDiff = filterDifficulty === "all" ? true : w.difficulty === filterDifficulty;
      return matchTopic && matchDiff;
    });
    deck = shuffle(source);
    current = 0;
    renderCard();
  }

  // ── Render current card ────────────────────────────────────
  function renderCard() {
    const counterEl = document.getElementById("counter");
    const topicBadge = document.getElementById("topic-badge");
    const cardArea = document.getElementById("card-area");
    const progressBar = document.getElementById("progress-bar");
    const revealBox = document.getElementById("reveal-box");
    const revealWord = document.getElementById("reveal-word");

    if (!deck.length) {
      counterEl.textContent = "No words";
      topicBadge.style.display = "none";
      cardArea.style.display = "none";
      progressBar.style.width = "0%";
      return;
    } else {
      cardArea.style.display = "flex";
    }
    
    const w = deck[current];
    revealed = false;

    // Counter & progress
    counterEl.textContent = `${current + 1} / ${deck.length}`;
    progressBar.style.width = `${((current + 1) / deck.length) * 100}%`;

    // Topic & Difficulty badge
    if (w.topic || w.difficulty) {
      const tText = w.topic || "Unknown";
      const dText = w.difficulty ? w.difficulty.charAt(0).toUpperCase() + w.difficulty.slice(1) : "Unknown";
      topicBadge.textContent = `${tText} • ${dText}`;
      topicBadge.style.display = "inline-block";
    } else {
      topicBadge.style.display = "none";
    }

    // Difficulty class on body
    document.body.dataset.difficulty = w.difficulty || "medium";

    // Info panels — reset to icon-only state
    collapseInfo();

    // Reveal box — reset
    revealBox.classList.remove("revealed");
    revealWord.textContent = "";
    revealBox.querySelector(".reveal-hint").style.display = "flex";
    revealWord.style.display = "none";
  }

  function collapseInfo() {
    ["pos", "meaning", "sentence"].forEach(key => {
      const panel = document.getElementById(key + "-panel");
      if(panel) panel.classList.remove("open");
    });
  }

  // ── Toggle info panels ─────────────────────────────────────
  function togglePanel(key) {
    const panel = document.getElementById(key + "-panel");
    const valEl = document.getElementById(key + "-value");
    const w = deck[current];
    if (!w || !panel || !valEl) return;

    if (panel.classList.contains("open")) {
      panel.classList.remove("open");
    } else {
      panel.classList.add("open");
      if (key === "pos") valEl.innerHTML = `<strong>${w.pos}</strong>`;
      if (key === "meaning") valEl.innerHTML = w.meaning;
      if (key === "sentence") valEl.innerHTML = `<em>"${w.sentence}"</em>`;
    }
  }

  // ── Reveal spelling ────────────────────────────────────────
  function revealSpelling() {
    if (revealed) return;
    revealed = true;
    const w = deck[current];
    const revealBox = document.getElementById("reveal-box");
    const revealWord = document.getElementById("reveal-word");

    revealBox.classList.add("revealed");
    revealBox.querySelector(".reveal-hint").style.display = "none";
    revealWord.style.display = "block";
    revealWord.textContent = w.word;
  }

  // ── Speech ─────────────────────────────────────────────────
  function speak(rate) {
    if (!window.speechSynthesis) return;
    window.speechSynthesis.cancel();
    const w = deck[current];
    if (!w) return;
    const utter = new SpeechSynthesisUtterance(w.word);
    utter.lang = "en-GB";
    utter.rate = rate;

    // Prefer a British English voice if available
    const voices = window.speechSynthesis.getVoices();
    const gbVoice = voices.find(v => v.lang === "en-GB") || null;
    if (gbVoice) utter.voice = gbVoice;

    window.speechSynthesis.speak(utter);
  }

  function listenNormal() { speak(1.0); }
  function listenSlow() { speak(0.6); }

  // ── Mark correct / incorrect ───────────────────────────────
  function markResult(correct) {
    const btnId = correct ? "btn-correct" : "btn-incorrect";
    const btn = document.getElementById(btnId);
    if (btn) {
      btn.classList.add("flash");
      setTimeout(() => btn.classList.remove("flash"), 400);
    }

    setTimeout(() => {
      if (current < deck.length - 1) {
        current++;
        renderCard();
      } else {
        showFinish();
      }
    }, 350);
  }

  // ── Finish screen ──────────────────────────────────────────
  function showFinish() {
    document.getElementById("card-area").style.display = "none";
    document.getElementById("finish-screen").style.display = "flex";
  }

  function restartDeck() {
    document.getElementById("finish-screen").style.display = "none";
    document.getElementById("card-area").style.display = "flex";
    loadDeck();
  }

  // ── Init ───────────────────────────────────────────────────
  function init() {
    buildFilters();

    // Attach Event Listeners to dropdowns dynamically
    document.getElementById("topic-filter").addEventListener("change", (e) => {
      filterTopic = e.target.value;
      loadDeck();
    });

    document.getElementById("difficulty-filter").addEventListener("change", (e) => {
      filterDifficulty = e.target.value;
      loadDeck();
    });

    loadDeck();
  }

  // Ensure DOM is fully loaded before executing initialization
  window.onload = init;

  </script>
</body>
</html>
