// ============================================================
//  SPELLING BEE PREP — WORD LIST
//  Add or remove words here. Never edit index.html or app.js.
//
//  Each word object supports these fields:
//    word        (required) — the correct British English spelling
//    pos         (required) — part of speech, e.g. "noun", "verb", "adjective"
//    meaning     (required) — a clear, concise definition
//    sentence    (required) — an example sentence using the word
//    difficulty  (optional) — "easy" | "medium" | "hard"  (default: "medium")
//    topic       (optional) — category label, e.g. "science", "literature"
// ============================================================

const WORDS = [
{ word: "acquiesce", pos: "verb", meaning: "To accept something reluctantly but without protest.",  sentence: "She decided to acquiesce to her teacher's suggestion and revise her essay.", difficulty: "hard",  topic: "behaviour"},
{ word: "conscientious", pos: "adjective", meaning: "Wishing to do one's work or duty well and thoroughly.", sentence: "The conscientious student double-checked every answer before submitting.", difficulty: "medium", topic: "character"},
{ word: "ephemeral", pos: "adjective", meaning: "Lasting for a very short time.", sentence: "The beauty of the cherry blossoms is ephemeral, fading within days.", difficulty: "hard", topic: "time"},
{ word: "liquefy", pos: "verb", meaning: "To make or become liquid.", sentence: "Extreme heat can liquefy metals that are usually solid.",  difficulty: "medium", topic: "science"},
{ word: "miscellaneous",  pos: "adjective",  meaning: "Of various types or from different sources; assorted.",  sentence: "The drawer was full of miscellaneous items with no obvious order.", difficulty: "medium",  topic: "general"},
{ word: "occurrence",  pos: "noun",  meaning: "An incident or event that takes place.",  sentence: "Rainfall in the desert is a rare occurrence.", difficulty: "easy",  topic: "general"},
{ word: "pharaoh",  pos: "noun",  meaning: "A ruler in ancient Egypt.",  sentence: "The pharaoh ordered the construction of a great pyramid.", difficulty: "medium",  topic: "history"},
{ word: "questionnaire",  pos: "noun",  meaning: "A set of printed or written questions with spaces for answers.", sentence: "Participants were asked to fill in a questionnaire about their habits.",  difficulty: "medium",  topic: "general"},
{ word: "supersede",  pos: "verb",  meaning: "To take the place of something previously in authority or use.",  sentence: "Digital cameras largely superseded film cameras in the early 2000s.",  difficulty: "hard", topic: "technology"},
{ word: "a/an", pos: "det", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "a few", pos: "det, adj & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "able", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "about", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "above", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "accident", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "across", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "act", pos: "n & v", meaning: "-", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "action", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "activity", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "actor", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "actually", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "ad", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "add", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "address", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "adult", pos: "adj & n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "advanced", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "adventure", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "advert", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "advertisement", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "advice", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "aeroplane", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "afraid", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "after", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "afternoon", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "afterwards", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "again", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "against", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "age", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "aged", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "ago", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "agree", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "air", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "airport", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "alarm clock", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Appliances" },
{ word: "album", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all", pos: "adv, det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all kinds of", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "allow", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all right/alright", pos: "adj, adv & exclam", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all sorts of", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "all the time", pos: "det", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "almost", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "alone", pos: "adj & adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "along", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "already", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "alright", pos: "adj, adv & exclam", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "also", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "always", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "a.m.", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "amazed", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "amazing", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "ambulance", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "among", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "an", pos: "det", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "and", pos: "conj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "angry", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "animal", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "another", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "answer", pos: "n & v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "any", pos: "det & pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anybody", pos: "pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anymore", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anyone", pos: "pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anything", pos: "pron", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anyway", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "anywhere", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "apartment", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "apartment building", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "app", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "apple", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "appointment", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "area", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "arm", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "armchair", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "around", pos: "adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "arrive", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "art", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "article", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Documents and Texts" },
{ word: "artist", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "as", pos: "conj & adv & prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "ask", pos: "v", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "assistant", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "as well", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "as well (as)", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "at", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "at / @", pos: "prep", meaning: "-", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "at all", pos: "prep phr", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "attractive", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "aunt", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "autumn", pos: "n", meaning: "-", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "available", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "away", pos: "adv", meaning: "-", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "awesome", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "awful", pos: "adj", meaning: "-", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "baby", pos: "n", meaning: "A very young child", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "back", pos: "adv, n & prep", meaning: "The rear part or return to a place", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "backpack", pos: "n", meaning: "A bag carried on the back", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bad", pos: "adj", meaning: "Not good; unpleasant", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "badly", pos: "adv", meaning: "In a way that is not good", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "badminton", pos: "n", meaning: "A sport played with rackets and a shuttlecock", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "bag", pos: "n", meaning: "A container used for carrying things", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "bake", pos: "v", meaning: "To cook in an oven", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "baker", pos: "n", meaning: "A person who makes bread and cakes", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "ball", pos: "n", meaning: "A round object used in games", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "balloon", pos: "n", meaning: "A small rubber bag filled with air", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "banana", pos: "n", meaning: "A long yellow fruit", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "band", pos: "n", meaning: "A group of musicians", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "bandage", pos: "n", meaning: "A cloth used to cover a wound", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "bank", pos: "n", meaning: "A place where money is kept", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "barbecue", pos: "n & v", meaning: "A meal cooked outdoors on a grill", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "baseball", pos: "n", meaning: "A game played with a bat and ball", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "basketball", pos: "n", meaning: "A game where you throw a ball through a hoop", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "bat", pos: "n", meaning: "Equipment used to hit a ball", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "bath", pos: "n & v", meaning: "Washing the body in a tub of water", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "bathing suit", pos: "n", meaning: "Clothes worn for swimming", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "bathroom", pos: "n", meaning: "A room for washing and using the toilet", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "bathtub", pos: "n", meaning: "A large container for washing the body", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "battery", pos: "n", meaning: "An object that provides electricity", sentence: "-", difficulty: "easy", topic: "Appliances" },
{ word: "be", pos: "v", meaning: "To exist or live", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "beach", pos: "n", meaning: "A sandy area by the sea", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "bean", pos: "n", meaning: "A seed of a plant used as food", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "bear", pos: "n", meaning: "A large, heavy wild animal", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "beard", pos: "n", meaning: "Hair growing on a man's chin", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "beautiful", pos: "adj", meaning: "Very attractive", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "because", pos: "conj", meaning: "For the reason that", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "become", pos: "v", meaning: "To begin to be something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "bed", pos: "n", meaning: "Furniture for sleeping", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "bedroom", pos: "n", meaning: "A room for sleeping", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "bee", pos: "n", meaning: "A yellow and black flying insect", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "beef", pos: "n", meaning: "Meat from a cow", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "before", pos: "adv, prep & conj", meaning: "Earlier than", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "begin", pos: "v", meaning: "To start", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "beginner", pos: "n", meaning: "A person starting to learn something", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "beginning", pos: "n", meaning: "The start of something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "behind", pos: "adv & prep", meaning: "At the back of", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "believe", pos: "v", meaning: "To think that something is true", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "bell", pos: "n", meaning: "A metal object that makes a ringing sound", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "belong", pos: "v", meaning: "To be the property of", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "below", pos: "adv & prep", meaning: "In a lower position", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "belt", pos: "n", meaning: "A strip of leather worn around the waist", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "beside", pos: "prep", meaning: "Next to", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "best", pos: "adj & adv", meaning: "Of the highest quality", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "better", pos: "adj & adv", meaning: "Higher in quality than something else", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "between", pos: "prep", meaning: "In the middle of two things", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "bicycle", pos: "n", meaning: "A vehicle with two wheels", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "big", pos: "adj", meaning: "Large in size", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "bike", pos: "n", meaning: "Short for bicycle or motorcycle", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bill", pos: "n", meaning: "A piece of paper showing money owed", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "bin", pos: "n", meaning: "A container for rubbish", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "biology", pos: "n", meaning: "The study of living things", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "bird", pos: "n", meaning: "An animal with feathers and wings", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "birth", pos: "n", meaning: "The time when a baby is born", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "birthday", pos: "n", meaning: "The day on which someone was born", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "biscuit", pos: "n", meaning: "A thin, flat, sweet cake", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "bit", pos: "n", meaning: "A small piece or amount", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "black", pos: "adj & n", meaning: "The darkest color", sentence: "-", difficulty: "easy", topic: "Colours" },
{ word: "blackboard", pos: "n", meaning: "A dark board used in schools", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "blanket", pos: "n", meaning: "A warm cover for a bed", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "block", pos: "n", meaning: "A large building or solid piece", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "blog", pos: "n", meaning: "A website with regular writing", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "blond(e)", pos: "adj", meaning: "Light-colored hair", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "blood", pos: "n", meaning: "Red liquid in the body", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "blouse", pos: "n", meaning: "A shirt for women", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "blue", pos: "adj & n", meaning: "The color of the sky", sentence: "-", difficulty: "easy", topic: "Colours" },
{ word: "board", pos: "n", meaning: "A flat piece of wood or card", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "board game", pos: "n", meaning: "A game played on a board", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "boat", pos: "n", meaning: "A small vehicle for traveling on water", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "body", pos: "n", meaning: "The whole physical structure of a person", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "boil", pos: "v", meaning: "To cook in very hot water", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "boiled", pos: "adj", meaning: "Cooked in boiling water", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "book", pos: "n & v", meaning: "Something to read or to reserve a place", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "bookcase", pos: "n", meaning: "A piece of furniture for books", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "booking", pos: "n", meaning: "A reservation", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bookshop", pos: "n", meaning: "A shop that sells books", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "boot", pos: "n", meaning: "A type of strong shoe covering the ankle", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "border", pos: "n", meaning: "The line between two countries", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bored", pos: "adj", meaning: "Feeling tired and unhappy because of no interest", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "boring", pos: "adj", meaning: "Not interesting", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "born", pos: "adj", meaning: "To come out of a mother's body", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "borrow", pos: "v", meaning: "To take something for a short time", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "boss", pos: "n", meaning: "A person in charge at work", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "both", pos: "det & pron", meaning: "Two people or things together", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "bottle", pos: "n", meaning: "A container for liquids", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "bottom", pos: "adj & n", meaning: "The lowest part of something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "bowl", pos: "n", meaning: "A round container for food", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "box", pos: "n", meaning: "A container with straight sides", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "boy", pos: "n", meaning: "A male child", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "boyfriend", pos: "n", meaning: "A male partner in a relationship", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "bracelet", pos: "n", meaning: "Jewellery worn around the wrist", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "brain", pos: "n", meaning: "The organ inside the head used for thinking", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "brake", pos: "n & v", meaning: "Something used to stop a vehicle", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bread", pos: "n", meaning: "A food made from flour and water", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "break", pos: "n & v", meaning: "To damage something or a short rest", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "breakfast", pos: "n", meaning: "The first meal of the day", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "bridge", pos: "n", meaning: "A structure built over a road or river", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bright", pos: "adj", meaning: "Full of light or intelligent", sentence: "-", difficulty: "easy", topic: "Colours" },
{ word: "brilliant", pos: "adj", meaning: "Very good or very bright", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "bring", pos: "v", meaning: "To take someone or something with you", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "broken", pos: "adj", meaning: "Damaged and not working", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "brother", pos: "n", meaning: "A male sibling", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "brown", pos: "adj & n", meaning: "The color of earth or wood", sentence: "-", difficulty: "easy", topic: "Colours" },
{ word: "brush", pos: "n & v", meaning: "An object used for cleaning or painting", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "build", pos: "v", meaning: "To make something by putting parts together", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "builder", pos: "n", meaning: "A person whose job is to build houses", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "building", pos: "n", meaning: "A structure with walls and a roof", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "burger", pos: "n", meaning: "Meat in a round bread roll", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "bus", pos: "n", meaning: "A large vehicle for many passengers", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "business", pos: "n", meaning: "Buying and selling goods or services", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "businessman", pos: "n", meaning: "A man who works in business", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "businesswoman", pos: "n", meaning: "A woman who works in business", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "bus station", pos: "n", meaning: "A place where buses start and end", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "bus stop", pos: "n", meaning: "A place where a bus stops for people", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "busy", pos: "adj", meaning: "Working hard or having a lot to do", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "but", pos: "conj", meaning: "Used to introduce a different statement", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "butter", pos: "n", meaning: "A yellow fat made from milk", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "butterfly", pos: "n", meaning: "An insect with large colored wings", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "buy", pos: "v", meaning: "To get something by paying money", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "by", pos: "prep", meaning: "Beside or near", sentence: "-", difficulty: "easy", topic: "General" },
 { word: "cabbage", pos: "n", meaning: "A large, round vegetable with green or purple leaves", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "cabinet", pos: "n", meaning: "A piece of furniture with shelves or drawers", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "cafe", pos: "n", meaning: "A place where you can buy drinks and simple meals", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "cafeteria", pos: "n", meaning: "A restaurant where you serve yourself", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "cake", pos: "n", meaning: "A sweet food made from flour, sugar, and eggs", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "calendar", pos: "n", meaning: "A list that shows the days, weeks, and months of the year", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "call", pos: "v", meaning: "To telephone someone or shout to them", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "camel", pos: "n", meaning: "A large animal with a humped back that lives in the desert", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "camera", pos: "n", meaning: "A device used for taking photos or videos", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "camp", pos: "v", meaning: "To stay in a tent for a short time", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "camping", pos: "n", meaning: "The activity of staying in a tent", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "campsite", pos: "n", meaning: "A place where people can put up tents", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "can/could", pos: "mv", meaning: "To be able to or to have permission", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "canal", pos: "n", meaning: "A man-made river for boats", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "candy", pos: "n", meaning: "Sweet food made mainly of sugar", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "cap", pos: "n", meaning: "A soft hat with a part that sticks out at the front", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "capital", pos: "n", meaning: "The most important city in a country", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "car", pos: "n", meaning: "A vehicle with four wheels used for travel", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "card", pos: "n", meaning: "Small piece of stiff paper or plastic", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "cardboard", pos: "n", meaning: "Very stiff, thick paper used for boxes", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "careful", pos: "adj", meaning: "Paying attention to what you are doing", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "carefully", pos: "adv", meaning: "Doing something with great attention", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "carpet", pos: "n", meaning: "Thick material used for covering floors", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "carrot", pos: "n", meaning: "A long, orange vegetable", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "carry", pos: "v", meaning: "To hold something and move it", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "cartoon", pos: "n", meaning: "A film or drawing that is funny", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "case", pos: "n", meaning: "A container for protecting or carrying things", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "cash", pos: "n", meaning: "Money in the form of notes and coins", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "castle", pos: "n", meaning: "A large building with high walls from the past", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "cat", pos: "n", meaning: "A small animal with fur often kept as a pet", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "catch", pos: "v", meaning: "To take hold of something that is moving", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "cathedral", pos: "n", meaning: "A very large and important church", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "cave", pos: "n", meaning: "A large hole in the side of a hill or cliff", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "CD", pos: "n", meaning: "A small disc used for storing music or information", sentence: "-", difficulty: "easy", topic: "Appliances" },
{ word: "CD player", pos: "n", meaning: "A machine that plays CDs", sentence: "-", difficulty: "easy", topic: "Appliances" },
{ word: "ceiling", pos: "n", meaning: "The top surface of a room", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "celebrate", pos: "v", meaning: "To do something special for an important event", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "celebration", pos: "n", meaning: "A special social event to celebrate something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "celebrity", pos: "n", meaning: "A famous person", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "cell phone", pos: "n", meaning: "A phone that you can carry with you", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "cent", pos: "n", meaning: "A unit of money in many countries", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "centimetre", pos: "n", meaning: "A unit of length", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "centre", pos: "n", meaning: "The middle point of something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "century", pos: "n", meaning: "A period of 100 years", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "cereal", pos: "n", meaning: "A food often eaten for breakfast with milk", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "certain", pos: "adj", meaning: "To be completely sure of something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "certainly", pos: "adv", meaning: "Without any doubt", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "chain", pos: "n", meaning: "Metal rings connected together", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "chair", pos: "n", meaning: "A seat with a back for one person", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "change", pos: "v & n", meaning: "To make something different or money returned", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "channel", pos: "n", meaning: "A television station", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "character", pos: "n", meaning: "A person in a book or film", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "chat", pos: "v & n", meaning: "To talk in a friendly way", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "cheap", pos: "adj", meaning: "Not costing a lot of money", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "check", pos: "v", meaning: "To look at something to see if it is correct", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "chef", pos: "n", meaning: "A professional cook", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "chemist", pos: "n", meaning: "A person who works in a shop selling medicine", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "chemistry", pos: "n", meaning: "The study of gases, liquids, and solids", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "cheque", pos: "n", meaning: "A printed form used instead of money", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "chess", pos: "n", meaning: "A game for two people played on a board", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "chicken", pos: "n", meaning: "A bird kept for its meat and eggs", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "child", pos: "n", meaning: "A young human who is not yet an adult", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "chilli", pos: "n", meaning: "A small vegetable that tastes very hot", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "chips", pos: "n", meaning: "Long, thin pieces of fried potato", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "chocolate", pos: "n", meaning: "A sweet brown food made from cocoa", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "choose", pos: "v", meaning: "To decide which thing you want", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "chop", pos: "v", meaning: "To cut something into smaller pieces", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "church", pos: "n", meaning: "A building used for Christian worship", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "cinema", pos: "n", meaning: "A place where you go to watch films", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "circle", pos: "n", meaning: "A round shape", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "city", pos: "n", meaning: "A large and important town", sentence: "-", difficulty: "easy", topic: "Places: Town and City" },
{ word: "class", pos: "n", meaning: "A group of students who learn together", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "classmate", pos: "n", meaning: "Someone who is in the same class as you", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "classroom", pos: "n", meaning: "A room in a school where lessons happen", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "clean", pos: "v & adj", meaning: "Not dirty or to remove dirt", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "cleaner", pos: "n", meaning: "A person whose job is to clean", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "clear", pos: "adj", meaning: "Easy to see through or understand", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "clearly", pos: "adv", meaning: "In a way that is easy to understand", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "clever", pos: "adj", meaning: "Quick at learning and understanding things", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "click", pos: "v & n", meaning: "To press a button on a computer mouse", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "climb", pos: "v", meaning: "To go up something using hands and feet", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "climbing", pos: "n", meaning: "The sport of going up rocks or mountains", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "clock", pos: "n", meaning: "A device that shows the time", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "close", pos: "v & adj", meaning: "To shut or near in distance", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "closed", pos: "adj", meaning: "Not open", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "closet", pos: "n", meaning: "A cupboard for clothes", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "clothes", pos: "n", meaning: "Things such as shirts and trousers that you wear", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "cloud", pos: "n", meaning: "A white or grey shape in the sky", sentence: "-", difficulty: "easy", topic: "Weather" },
{ word: "cloudy", pos: "adj", meaning: "With many clouds in the sky", sentence: "-", difficulty: "easy", topic: "Weather" },
{ word: "clown", pos: "n", meaning: "A performer who makes people laugh", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "club", pos: "n", meaning: "An organization for people with same interests", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "coach", pos: "n", meaning: "A bus for long journeys or a trainer", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "coast", pos: "n", meaning: "The land next to the sea", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "coat", pos: "n", meaning: "A piece of clothing worn over other clothes", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "coffee", pos: "n", meaning: "A popular hot dark drink", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "cola", pos: "n", meaning: "A sweet, dark fizzy drink", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "cold", pos: "adj & n", meaning: "Having a low temperature or an illness", sentence: "-", difficulty: "easy", topic: "Weather" },
{ word: "colleague", pos: "n", meaning: "A person you work with", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "collect", pos: "v", meaning: "To get things from different places", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "collection", pos: "n", meaning: "A group of objects brought together", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "college", pos: "n", meaning: "A place where students go after school", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "colour", pos: "n & v", meaning: "Red, blue, green, etc.", sentence: "-", difficulty: "easy", topic: "Colours" },
{ word: "comb", pos: "n & v", meaning: "An object used to make hair tidy", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "come", pos: "v", meaning: "To move toward a place", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "comfortable", pos: "adj", meaning: "Making you feel physically relaxed", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "comic", pos: "n", meaning: "A magazine with stories told in pictures", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "company", pos: "n", meaning: "An organization that sells goods or services", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "competition", pos: "n", meaning: "An event where people try to win", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "complain", pos: "v", meaning: "To say that you are not happy about something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "complete", pos: "v & adj", meaning: "To finish or having all parts", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "computer", pos: "n", meaning: "An electronic machine for storing data", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "concert", pos: "n", meaning: "A performance of music", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "congratulate", pos: "v", meaning: "To tell someone you are happy for their success", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "congratulations", pos: "exclam", meaning: "Something you say to celebrate success", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "contact", pos: "v & n", meaning: "To communicate with someone", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "continue", pos: "v", meaning: "To keep doing something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "conversation", pos: "n", meaning: "A talk between two or more people", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "cook", pos: "v & n", meaning: "To prepare food or the person who does it", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "cooker", pos: "n", meaning: "A piece of kitchen equipment used for cooking", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "cookie", pos: "n", meaning: "A small, flat, sweet cake", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "cooking", pos: "n", meaning: "The activity of preparing food", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "cool", pos: "adj & exclam", meaning: "Slightly cold or very good", sentence: "-", difficulty: "easy", topic: "Weather" },
{ word: "copy", pos: "v", meaning: "To make something exactly like something else", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "corner", pos: "n", meaning: "The point where two lines or roads meet", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "correct", pos: "adj", meaning: "Accurate or right", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "cost", pos: "n & v", meaning: "The amount of money needed to buy something", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "costume", pos: "n", meaning: "Clothes worn by an actor or for a party", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "couch", pos: "n", meaning: "A long, soft seat for two or more people", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "could", pos: "mv", meaning: "Past tense of 'can'", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "count", pos: "v", meaning: "To see how many things there are", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "country", pos: "n", meaning: "An area of land with its own government", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "countryside", pos: "n", meaning: "Land that is not in towns or cities", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "course", pos: "n", meaning: "A set of lessons or a part of a meal", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "court", pos: "n", meaning: "An area for playing games like tennis", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "cousin", pos: "n", meaning: "The child of your aunt or uncle", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "cover", pos: "v", meaning: "To put something over something else", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "cow", pos: "n", meaning: "A large farm animal kept for milk or meat", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "crazy", pos: "adj", meaning: "Stupid or strange", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "cream", pos: "n", meaning: "A thick liquid made from milk", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "create", pos: "v", meaning: "To make something new", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "creative", pos: "adj", meaning: "Good at thinking of new ideas", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "cricket", pos: "n", meaning: "A sport played with a bat and ball by two teams", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "cross", pos: "v & n", meaning: "To go from one side to the other", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "crossing", pos: "n", meaning: "A place where you can safely cross a road", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "crowd", pos: "n", meaning: "A large group of people together", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "crowded", pos: "adj", meaning: "Full of people", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "cry", pos: "v", meaning: "To produce tears because you are sad", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "cucumber", pos: "n", meaning: "A long, green vegetable eaten in salads", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "cup", pos: "n", meaning: "A small container used for drinking tea or coffee", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "cupboard", pos: "n", meaning: "A piece of furniture with doors for storage", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "curry", pos: "n", meaning: "A spicy dish often served with rice", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "curtain", pos: "n", meaning: "A piece of material hung to cover a window", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "customer", pos: "n", meaning: "A person who buys things from a shop", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "cut", pos: "v", meaning: "To use a knife or scissors to divide something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "cycling", pos: "n", meaning: "The activity of riding a bicycle", sentence: "-", difficulty: "easy", topic: "Sport" }, 
  { word: "dad", pos: "n", meaning: "A father", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "daily", pos: "adj & adv", meaning: "Happening every day", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "dance", pos: "n & v", meaning: "To move your body to music", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "dancer", pos: "n", meaning: "A person who dances", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "dancing", pos: "n", meaning: "The activity of moving to music", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "danger", pos: "n", meaning: "The possibility of harm or death", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "dangerous", pos: "adj", meaning: "Likely to cause harm", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "dark", pos: "adj & n", meaning: "With little or no light", sentence: "-", difficulty: "easy", topic: "Colours" },
{ word: "date", pos: "n", meaning: "A specific day of the month or year", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "daughter", pos: "n", meaning: "A female child", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "day", pos: "n", meaning: "A period of 24 hours", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "dead", pos: "adj", meaning: "Not living anymore", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "dear", pos: "adj", meaning: "Used to start a letter or meaning expensive", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "decide", pos: "v", meaning: "To make a choice about something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "deep", pos: "adj", meaning: "Going a long way down from the surface", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "degree", pos: "n", meaning: "A unit for measuring temperature or an academic qualification", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "delay", pos: "n & v", meaning: "To make something happen later than planned", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "delicious", pos: "adj", meaning: "Having a very good taste", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "deliver", pos: "v", meaning: "To take goods to a person or place", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "dentist", pos: "n", meaning: "A doctor who looks after teeth", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "department", pos: "n", meaning: "A part of an organization or shop", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "department store", pos: "n", meaning: "A large shop divided into several parts", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "depend (on)", pos: "v", meaning: "To need or be influenced by something else", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "describe", pos: "v", meaning: "To say what someone or something is like", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "desert", pos: "n", meaning: "A large, dry, sandy area of land", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "desk", pos: "n", meaning: "A table that you sit at to write or work", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "dessert", pos: "n", meaning: "Sweet food eaten at the end of a meal", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "details", pos: "n", meaning: "Small facts or pieces of information", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "diary", pos: "n", meaning: "A book where you write daily records", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "dictionary", pos: "n", meaning: "A book that explains the meanings of words", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "die", pos: "v", meaning: "To stop living", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "difference", pos: "n", meaning: "The way in which things are not the same", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "different", pos: "adj", meaning: "Not the same", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "difficult", pos: "adj", meaning: "Not easy to do or understand", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "digital", pos: "adj", meaning: "Recording or storing information as series of numbers", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "digital camera", pos: "n", meaning: "A camera that stores pictures as digital files", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "dinner", pos: "n", meaning: "The main meal of the day", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "dinosaur", pos: "n", meaning: "An extinct type of very large reptile", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "diploma", pos: "n", meaning: "A certificate showing you completed a course", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "directions", pos: "n", meaning: "Instructions on how to get somewhere", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "dirty", pos: "adj", meaning: "Not clean", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "disco", pos: "n", meaning: "A place or event where people dance to music", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "discount", pos: "n", meaning: "A reduction in the usual price", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "discover", pos: "v", meaning: "To find out something for the first time", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "discuss", pos: "v", meaning: "To talk about something with someone", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "dish", pos: "n", meaning: "A container for food or a specific type of food", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "distance", pos: "n", meaning: "The amount of space between two places", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "do", pos: "v", meaning: "To perform an action or activity", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "doctor / Dr", pos: "n", meaning: "A person whose job is to treat sick people", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "document", pos: "n", meaning: "A piece of paper or computer file with information", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "dog", pos: "n", meaning: "A common animal often kept as a pet", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "doll", pos: "n", meaning: "A toy that looks like a small person", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "dollar", pos: "n", meaning: "The unit of money in the US and other countries", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "dolphin", pos: "n", meaning: "An intelligent sea animal", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "door", pos: "n", meaning: "The way into a room or building", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "dot", pos: "n", meaning: "A small round mark", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "double", pos: "adj", meaning: "Twice as much or twice as many", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "down", pos: "adv & prep", meaning: "Towards a lower place", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "download", pos: "n & v", meaning: "To move information from the internet to a computer", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "downstairs", pos: "adv", meaning: "On a lower floor of a building", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "draw", pos: "v", meaning: "To make a picture with a pen or pencil", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "drawer", pos: "n", meaning: "A part of a piece of furniture that slides out", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "drawing", pos: "n", meaning: "A picture made with a pen or pencil", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "dream", pos: "n & v", meaning: "Images in your mind while sleeping", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "dress", pos: "n & v", meaning: "A piece of clothing for women or to put on clothes", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "dressed", pos: "adj", meaning: "Wearing clothes", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "drink", pos: "n & v", meaning: "Liquid that you swallow", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "drive", pos: "v & n", meaning: "To control a vehicle", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "driver", pos: "n", meaning: "A person who drives a vehicle", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "driving licence", pos: "n", meaning: "A document that allows you to drive", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "drop", pos: "v", meaning: "To let something fall", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "drug", pos: "n", meaning: "A medicine or illegal substance", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "drugstore", pos: "n", meaning: "A shop where you buy medicine", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "drum", pos: "n", meaning: "A musical instrument played by hitting it", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "dry", pos: "adj & v", meaning: "Not wet", sentence: "-", difficulty: "easy", topic: "Weather" },
{ word: "duck", pos: "n", meaning: "A common water bird", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "during", pos: "prep", meaning: "At a time within a period", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "DVD", pos: "n", meaning: "A disc for storing movies or data", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "DVD player", pos: "n", meaning: "A machine that plays DVDs", sentence: "-", difficulty: "easy", topic: "Appliances" },
{ word: "each", pos: "det & pron", meaning: "Every one of two or more things or people", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "ear", pos: "n", meaning: "The part of the body that you hear with", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "early", pos: "adj & adv", meaning: "Near the beginning of a period of time", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "earn", pos: "v", meaning: "To get money for the work you do", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "earring", pos: "n", meaning: "A piece of jewellery that you wear on your ear", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "easily", pos: "adv", meaning: "With no difficulty", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "east", pos: "adj, adv & n", meaning: "The direction where the sun rises", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "Easter", pos: "n", meaning: "A Christian holiday in the spring", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "easy", pos: "adj", meaning: "Not difficult", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "eat", pos: "v", meaning: "To put food into your mouth and swallow it", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "edge", pos: "n", meaning: "The part of something that is furthest from the center", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "education", pos: "n", meaning: "The process of teaching and learning in a school", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "egg", pos: "n", meaning: "An oval object produced by a bird, eaten as food", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "electric", pos: "adj", meaning: "Using or producing electricity", sentence: "-", difficulty: "easy", topic: "Appliances" },
{ word: "electricity", pos: "n", meaning: "A type of energy used for heating and lighting", sentence: "-", difficulty: "easy", topic: "Appliances" },
{ word: "elephant", pos: "n", meaning: "A very large grey animal with a long trunk", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "elevator", pos: "n", meaning: "A machine that carries people up and down in a building", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "else", pos: "adv", meaning: "In addition to someone or something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "email", pos: "n & v", meaning: "A message sent by computer", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "embarrassed", pos: "adj", meaning: "Feeling ashamed or shy", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "embarrassing", pos: "adj", meaning: "Making you feel embarrassed", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "empty", pos: "adj", meaning: "With nothing inside", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "end", pos: "n & v", meaning: "The final part of something or to finish", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "engine", pos: "n", meaning: "The part of a vehicle that makes it move", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "engineer", pos: "n", meaning: "A person whose job is to design or build machines", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "enjoy", pos: "v", meaning: "To get pleasure from something", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "enough", pos: "adv, det & pron", meaning: "As much as is necessary", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "enter", pos: "v", meaning: "To go into a place", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "entrance", pos: "n", meaning: "A door or gate that you go through to enter a place", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "envelope", pos: "n", meaning: "A flat paper container for a letter", sentence: "-", difficulty: "easy", topic: "Communication and Technology" },
{ word: "environment", pos: "n", meaning: "The air, water, and land around us", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "equipment", pos: "n", meaning: "The things that are used for a particular activity", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "eraser", pos: "n", meaning: "A small object used to remove pencil marks", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "especially", pos: "adv", meaning: "More than other things or people", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "euro", pos: "n", meaning: "The unit of money used in many European countries", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "even", pos: "adv", meaning: "Used to emphasize something unexpected", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "evening", pos: "n", meaning: "The part of the day between afternoon and night", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "ever", pos: "adv", meaning: "At any time", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "every", pos: "det", meaning: "Each one of a group", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "everybody", pos: "pron", meaning: "Every person", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "everyone", pos: "pron", meaning: "Every person; everybody", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "everything", pos: "pron", meaning: "All things", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "everywhere", pos: "adv", meaning: "In every place", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "exactly", pos: "adv", meaning: "Used to emphasize that something is completely correct", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "exam", pos: "n", meaning: "A test of what you know or can do", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "examination", pos: "n", meaning: "A formal test; an exam", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "examine", pos: "v", meaning: "To look at something carefully", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "example", pos: "n", meaning: "Something that represents a group of things", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "excellent", pos: "adj", meaning: "Very good", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "except", pos: "prep", meaning: "Not including", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "excited", pos: "adj", meaning: "Feeling very happy and enthusiastic", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "exciting", pos: "adj", meaning: "Making you feel excited", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "excuse", pos: "v", meaning: "To forgive someone for a small mistake", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "exercise", pos: "n & v", meaning: "Physical activity to keep fit", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "exhibition", pos: "n", meaning: "A public show of art or objects", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "exit", pos: "n", meaning: "A door or way out of a place", sentence: "-", difficulty: "easy", topic: "Places: Buildings" },
{ word: "expensive", pos: "adj", meaning: "Costing a lot of money", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "explain", pos: "v", meaning: "To make something easy to understand", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "explorer", pos: "n", meaning: "A person who travels to new places to learn about them", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "extra", pos: "adj, adv & n", meaning: "More than is usual or expected", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "face", pos: "n", meaning: "The front part of the head with eyes, nose, and mouth", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "fact", pos: "n", meaning: "Something that is known to be true", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "factory", pos: "n", meaning: "A building where things are made by machines", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "fail", pos: "v", meaning: "To not succeed in doing something or passing a test", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "fair", pos: "adj", meaning: "Treating everyone in the same way or light-colored hair", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "fall", pos: "v", meaning: "To move down toward the ground quickly", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "family", pos: "n", meaning: "A group of people who are related to each other", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "famous", pos: "adj", meaning: "Known by many people", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "fan", pos: "n", meaning: "Someone who likes a person, sport, or group very much", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "fantastic", pos: "adj", meaning: "Very good; wonderful", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "far", pos: "adv & adj", meaning: "At a great distance", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "farm", pos: "n", meaning: "Land used for growing crops or keeping animals", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "farmer", pos: "n", meaning: "A person who owns or manages a farm", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "fashion", pos: "n", meaning: "A popular style of clothes or behavior", sentence: "-", difficulty: "easy", topic: "Clothes and Accessories" },
{ word: "fast", pos: "adj & adv", meaning: "Moving or happening quickly", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "fast food", pos: "n", meaning: "Food that is made and served very quickly", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "fat", pos: "adj", meaning: "Having a lot of extra flesh on the body", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "father", pos: "n", meaning: "A male parent", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "favourite", pos: "adj & n", meaning: "The person or thing that you like best", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "feel", pos: "v", meaning: "To experience an emotion or physical sensation", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "feelings", pos: "n", meaning: "Emotions such as happiness, sadness, or anger", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "ferry", pos: "n", meaning: "A boat that carries people and cars across water", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "festival", pos: "n", meaning: "A special time of celebration", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "few", pos: "adj, det & pron", meaning: "A small number of things or people", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "field", pos: "n", meaning: "An area of land used for animals or crops", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "fight", pos: "v & n", meaning: "To use physical force or argue with someone", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "fill", pos: "v", meaning: "To make something full", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "film", pos: "n & v", meaning: "A story shown in moving pictures", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "film maker", pos: "n", meaning: "A person who makes films", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "film star", pos: "n", meaning: "A famous actor in films", sentence: "-", difficulty: "easy", topic: "Entertainment and Media" },
{ word: "final", pos: "adj & n", meaning: "The last part of something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "finally", pos: "adv", meaning: "After a long time or at the end", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "find", pos: "v", meaning: "To discover something by looking for it", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "find out", pos: "phr v", meaning: "To get information about something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "fine", pos: "adj & n", meaning: "Good, well, or thin", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "finger", pos: "n", meaning: "One of the five long parts at the end of the hand", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "finish", pos: "v & n", meaning: "To complete something or reach the end", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "finished", pos: "adj", meaning: "Completed or no longer existing", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "fire", pos: "n", meaning: "Heat and light from something burning", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "firefighter", pos: "n", meaning: "A person whose job is to stop fires", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "first", pos: "adv & adj", meaning: "Coming before all others", sentence: "-", difficulty: "easy", topic: "Time" },
{ word: "first name", pos: "n", meaning: "The name given to you when you are born", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "fish", pos: "n & v", meaning: "An animal that lives and swims in water", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "fishing", pos: "n", meaning: "The sport or job of catching fish", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "fit", pos: "adj & v", meaning: "Healthy and strong or the right size", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "flat", pos: "adj & n", meaning: "A set of rooms for living in; a level surface", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "flight", pos: "n", meaning: "A journey in an aircraft", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "floor", pos: "n", meaning: "The surface you walk on inside a building", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "flower", pos: "n", meaning: "The colored part of a plant", sentence: "-", difficulty: "easy", topic: "The Natural World" },
{ word: "fly", pos: "v & n", meaning: "To move through the air", sentence: "-", difficulty: "easy", topic: "Travel and Transport" },
{ word: "fog", pos: "n", meaning: "Thick clouds near the ground that make it hard to see", sentence: "-", difficulty: "easy", topic: "Weather" },
{ word: "foggy", pos: "adj", meaning: "With a lot of fog", sentence: "-", difficulty: "easy", topic: "Weather" },
{ word: "folder", pos: "n", meaning: "A cover for keeping loose papers together", sentence: "-", difficulty: "easy", topic: "Education" },
{ word: "follow", pos: "v", meaning: "To move behind someone or obey rules", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "food", pos: "n", meaning: "Something that people and animals eat to live", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "foot", pos: "n", meaning: "The part of the body at the bottom of the leg", sentence: "-", difficulty: "easy", topic: "Health, Medicine and Exercise" },
{ word: "football", pos: "n", meaning: "A game where two teams kick a ball", sentence: "-", difficulty: "easy", topic: "Sport" },
{ word: "footballer", pos: "n", meaning: "A person who plays football", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "football player", pos: "n", meaning: "A person who plays football", sentence: "-", difficulty: "easy", topic: "Work and Jobs" },
{ word: "for", pos: "prep", meaning: "Used to show purpose or destination", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "foreign", pos: "adj", meaning: "From another country", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "forest", pos: "n", meaning: "A large area of trees", sentence: "-", difficulty: "easy", topic: "Places: Countryside" },
{ word: "forget", pos: "v", meaning: "To not remember something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "fork", pos: "n", meaning: "A tool with prongs used for eating", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "form", pos: "n", meaning: "A document with spaces to write information", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "free", pos: "adj & adv", meaning: "Costing no money or available", sentence: "-", difficulty: "easy", topic: "Shopping" },
{ word: "french fries", pos: "n", meaning: "Thin pieces of fried potato", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "fresh", pos: "adj", meaning: "Recently made or picked; not old", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "fridge", pos: "n", meaning: "A machine that keeps food cold", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "friend", pos: "n", meaning: "A person you know well and like", sentence: "-", difficulty: "easy", topic: "Family and Friends" },
{ word: "friendly", pos: "adj", meaning: "Kind and pleasant", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "frightened", pos: "adj", meaning: "Feeling afraid or scared", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "frightening", pos: "adj", meaning: "Making you feel afraid", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "from", pos: "prep", meaning: "Used to show the origin of something", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "front", pos: "adj & n", meaning: "The part of something that faces forward", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "fruit", pos: "n", meaning: "The sweet part of a plant that contains seeds", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "fry", pos: "v", meaning: "To cook in hot fat or oil", sentence: "-", difficulty: "easy", topic: "Food and Drink" },
{ word: "full", pos: "adj", meaning: "Containing as much as possible", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "fun", pos: "adj & n", meaning: "Enjoyable and pleasant", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "funny", pos: "adj", meaning: "Making you laugh", sentence: "-", difficulty: "easy", topic: "Personal Feelings, Opinions and Experiences" },
{ word: "furniture", pos: "n", meaning: "Things such as chairs and tables", sentence: "-", difficulty: "easy", topic: "House and Home" },
{ word: "further", pos: "adv & adj", meaning: "At a greater distance; more", sentence: "-", difficulty: "easy", topic: "General" },
{ word: "future", pos: "adj & n", meaning: "The time that will come after now", sentence: "-", difficulty: "easy", topic: "Time" },  
{ word: "threshold", pos: "noun", meaning: "The level or point at which something starts to happen.", sentence: "The noise had reached the threshold at which it became unbearable.", difficulty: "easy", topic: "science"}
];
